---
- name: Install PECL dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_pecl_apt_packages

- name: Install PECL extensions
  shell: echo "\n\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php_pecl_extensions
  tags: [packages,php]

- name: Create PECL extensions .ini files
  template: src=extension.ini.j2 dest={{ php_conf_dir }}/{{ item }}.ini owner=root group=root mode=0644
  with_items: php_pecl_extensions

- name: Enabling xdebug config in PHP cli conf
  sudo: yes
  file: src={{ php_conf_dir }}/{{item}}.ini  dest=/etc/php5/cli/conf.d/20-{{item}}.ini state=link
  with_items: php_pecl_extensions

- name: Enabling xdebug config in PHP fpm conf
  sudo: yes
  file: src={{ php_conf_dir }}/{{item}}.ini  dest=/etc/php5/fpm/conf.d/20-{{item}}.ini state=link
  with_items: php_pecl_extensions
  notify:  reload php-fpm