---
# Create Erlang distributed app

- name: start rabbitmq server
  service: name=rabbitmq-server state=started

- name: stop rabbitmq app
  shell: rabbitmqctl stop_app

- name: resetting rabbitmq app
  shell: rabbitmqctl reset

- name: add this node to cluster
  shell: rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}

- name: start rabbitmq app
  shell: rabbitmqctl start_app

