---

rabbitmq_erlang_cookie: 1qa2ws3ed
rabbitmq_ulimit_open_files: 1024
rabbitmq_create_cluster: no
rabbitmq_cluster_master: localhost
rabbitmq_vhosts: []

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_users:
  - user: admin
    password: admin
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

rabbitmq_users_removed:
  - guest

